GSG-G11/team-5-ecommerce-app

.vscode/settings.json
README.md

- update title project in the readme file
-  update description project in the readme file
R #1

Update Readme File

---

.gitignore
index.html
package.json
test/test.js

-  Create index.html
-  CSS Folder Have CSS files
-  Js Folder Have Js Files
-  test Folder Have file test
-  image Folder have images
-  install jest for test and configuration it.
R #3

Build File structure

---

.vscode/settings.json
data/categories.json
data/products.json

-  Create Fack product Data
- Create Fack Category product Data
R #5

create fack product and Categories data

---

js/logic.js
test/test.js

-  Create Test
-  Add #Product
-  Delete Product

Create test and logic for product add and delete

---

data/categories.json
data/products.json

- edit the categories names
- edit products data

edit data json file

---

.editorconfig
js/logic.js
test/test.js

create (filter, sort) functions test & logic for products

---

css/cart.css
index.html

RELATES#14
create cart section that contains items the Buyer what are want buy

create static cart

---

css/cart.css

RELATES#20
add responsive style for cart section

add responsive for cart section

---

css/cart.css
css/modal.css
css/style.css
index.html

- remove Root Variable and Global Style From all pages then add For one page
-  in line 30 in cart.css,
-  in line 75 in index.html, add class 'cart-hidden'
R #24

Fix Style and remove Style

---

css/modal.css
css/style.css
index.html
js/app.js

Create a popup screen For Create product

---

css/modal.css
css/style.css
index.html
js/app.js

create get post products localstorage

---

css/modal.css
css/style.css
index.html
js/app.js
js/logic.js
test/test.js

add a product to local.
add local storage.
R #29

create products function add product to local and local storage

---

css/style.css
js/app.js

switch between buyer and seller

---

index.html
js/app.js

42 total price

---

js/app.js
js/logic.js
test/test.js

delete products function and from local storage

delete products function and from local storage

---

js/app.js
js/logic.js
test/test.js

sort filter products

---

index.html
js/app.js

Fix create and delete the product
R #48

Fix create and delete product

---

index.html
js/app.js

Create function for update and save in local storage
R #52

Create function for update and save in local storage

---

css/style.css
js/app.js

create toggle view gird list function

---

index.html
js/app.js

add item to cart and update number of items in cart and in navbar

47 add item to cart

---

css/style.css
js/app.js
js/logic.js
test/test.js

create search function by name of product

---

js/app.js

57 delete item

---

css/cart.css
js/app.js

background
